# Generated by Django 6.0.4 on 2026-05-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
